version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"  # Le port hôte est maintenant 27018
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=projet-fileRouge

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017/projet-fileRouge
      - PORT=3001
      - JWT_SECRET=CleJWTAPPLINDF
    depends_on:
      - mongodb
    restart: unless-stopped

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - PORT_CLIENT=3002
    restart: unless-stopped

  fournisseur:
    build: 
      context: ./fournisseur
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./fournisseur:/app
      - /app/node_modules
    environment:
      - PORT_FOURNISSEUR=3000
    restart: unless-stopped

volumes:
  mongodb_data: